In [ ]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
df = pd.read_csv('/content/diabetes.csv')
X = df[df.columns[:-1]]
y = df['Outcome']

X = X.values
y = torch.tensor(y.values)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
ms = MinMaxScaler()
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)
y_train = ms.fit_transform(y_train)
y_test = ms.transform(y_test)

In [ ]:
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)
print(X_train, X_test)
print(y_train, y_test)

(514, 8) (254, 8)
(514, 1) (254, 1)
[[ 1.89917664 -0.19475093  1.55717838 ... -1.04293476  1.60661512
   0.06905859]
 [ 0.98286551  0.64046336 -0.55496107 ... -0.4148062   0.62609815
   2.37289284]
 [ 0.06655438 -0.16381707  0.11203033 ... -1.29156898 -0.02953111
   0.32504017]
 ...
 [ 1.89917664 -0.62782501  0.89018698 ...  1.78364376  1.94028358
   0.41036736]
 [-1.1551938   0.6095295  -3.88991811 ...  1.36489138 -0.78467552
  -0.35757739]
 [-1.1551938   0.11458769  1.44601315 ... -1.23922494 -0.61784129
  -1.04019494]] [[ 0.67742846 -0.7206266  -0.66612631 ...  0.2656664  -0.12611934
   0.83700334]
 [-0.54431971 -0.28755252  0.27877819 ...  0.4881286  -0.95150975
  -1.04019494]
 [-0.54431971 -0.41128797 -0.3326306  ... -0.15308597 -0.92224058
  -1.04019494]
 ...
 [-0.84975676 -3.75214514  0.22319557 ... -0.55875233 -0.50954538
  -1.04019494]
 [ 1.28830255  0.67139722 -0.22146537 ...  0.38344051 -1.00712116
   0.66634895]
 [-0.54431971 -0.62782501 -0.66612631 ... -1.01676274  0.41243

In [ ]:
# minmaxscaler only
from sklearn.preprocessing import MinMaxScaler
minMaxScaler = MinMaxScaler()
minMaxScaler.fit(X_train)
tran_data_minMaxScaled = minMaxScaler.transform(X_train)

In [ ]:
print(tran_data_minMaxScaled)

[[0.58823529 0.57788945 0.80327869 ... 0.35767511 0.4030743  0.21666667]
 [0.41176471 0.71356784 0.49180328 ... 0.42921013 0.26003416 0.66666667]
 [0.23529412 0.58291457 0.59016393 ... 0.32935917 0.16438941 0.26666667]
 ...
 [0.58823529 0.50753769 0.70491803 ... 0.67958271 0.45175064 0.28333333]
 [0.         0.70854271 0.         ... 0.6318927  0.05422716 0.13333333]
 [0.         0.6281407  0.78688525 ... 0.33532042 0.07856533 0.        ]]


In [ ]:
# StandardScaler only
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
standardScaler.fit(X_train)
tran_data_standardScaled = standardScaler.transform(X_train)

In [ ]:
print(tran_data_standardScaled)

[[ 1.89917664 -0.19475093  1.55717838 ... -1.04293476  1.60661512
   0.06905859]
 [ 0.98286551  0.64046336 -0.55496107 ... -0.4148062   0.62609815
   2.37289284]
 [ 0.06655438 -0.16381707  0.11203033 ... -1.29156898 -0.02953111
   0.32504017]
 ...
 [ 1.89917664 -0.62782501  0.89018698 ...  1.78364376  1.94028358
   0.41036736]
 [-1.1551938   0.6095295  -3.88991811 ...  1.36489138 -0.78467552
  -0.35757739]
 [-1.1551938   0.11458769  1.44601315 ... -1.23922494 -0.61784129
  -1.04019494]]


In [ ]:
# customdataset
class customdataset(Dataset):
  def __init__(self, X, y):
    self.X = X
    self.y = y
    self.len = len(self.X)

  def __getitem__(self, index):
    return self.X[index], self.y[index]

  def __len__(self):
    return self.len

In [ ]:
train_data = customdataset(torch.FloatTensor(X_train), torch.FloatTensor(y_train))
test_data = customdataset(torch.FloatTensor(X_test), torch.FloatTensor(y_test))

train_loader = DataLoader(dataset=train_data, batch_size=64, shuffle=True)
test_loader = DataLoader(dataset=test_data, batch_size=64, shuffle=False)

In [ ]:
class binaryClassification(nn.Module):
  def __init__(self):
    super(binaryClassification, self).__init__()
    self.layer_1 == nn.Linear(8, 64, bias=True)
    self.layer_2 == nn.Linear(64, 64, bias=True)
    self.layer_out = nn.Linear(64, 1, bias=True)
    self.relu = nn.ReLU()
    self.dropout = nn.Dropout(p=0.1)
    self.batchnorm1 = nn.BatchNorm1d(64)
    self.batchnorm2 = nn.BatchNorm1d(64)

  def forward(self, inputs):
    x = self.relu(self.layer_1(inputs))
    x = self.batchnorm1(x)
    x = self.relu(self.layer_2(x))
    x = self.batchnorm2(x)
    x = self.dropout(x)
    x = self.layer_out(x)

    return x

In [ ]:
class binaryClassification(nn.Module):
  def __init__(self):
    super(binaryClassification, self).__init__()
    self.layer_1 = nn.Linear(8, 64, bias=True) # Changed == to =
    self.layer_2 = nn.Linear(64, 64, bias=True) # Changed == to =
    self.layer_out = nn.Linear(64, 1, bias=True)
    self.relu = nn.ReLU()
    self.dropout = nn.Dropout(p=0.1)
    self.batchnorm1 = nn.BatchNorm1d(64)
    self.batchnorm2 = nn.BatchNorm1d(64)

  def forward(self, inputs):
    x = self.relu(self.layer_1(inputs))
    x = self.batchnorm1(x)
    x = self.relu(self.layer_2(x))
    x = self.batchnorm2(x)
    x = self.dropout(x)
    x = self.layer_out(x)

    return x

In [ ]:
epochs = 1000 + 1
print_epochs = 100
learning_rate = 1e-2

model = binaryClassification()
model.to(device)
print(model)

BCE = nn.BCEWithLogitsLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

binaryClassification(
  (layer_1): Linear(in_features=8, out_features=64, bias=True)
  (layer_2): Linear(in_features=64, out_features=64, bias=True)
  (layer_out): Linear(in_features=64, out_features=1, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.1, inplace=False)
  (batchnorm1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (batchnorm2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)


In [ ]:
def accuracy(y_pred, y_test):
  y_pred_tag = torch.round(torch.sigmoid(y_pred))
  correct_results_sum = (y_pred_tag == y_test).sum().float()
  acc = correct_results_sum / y_test.shape[0]
  acc = torch.round(acc * 100)

  return acc

In [ ]:
for epoch in range(epochs):
  iteration_loss = 0
  iteration_accuracy = 0

  model.train()
  for i, data in enumerate(train_loader):
    X, y = data
    y_pred = model(X.float())
    loss = BCE(y_pred, y.reshape(-1,1).float())

    iteration_loss += loss
    iteration_accuracy += accuracy(y_pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  if epoch % print_epochs == 0:
    print('Train: epoch: {0} -loss: {1:.5f}; acc:{2:.3f}'.format(epoch, iteration_loss/(i+1), iteration_accuracy/(i+1)))

  iteration_loss = 0
  iteration_accuracy = 0
  model.eval()
  for i, data in enumerate(test_loader):
    X, y = data
    y_pred = model(X.float())
    loss = BCE(y_pred, y.reshape(-1,1).float())
    iteration_loss += loss
    iteration_accuracy += accuracy(y_pred, y)
  if (epoch % print_epochs == 0):
    print('Test: epoch: {0} -loss: {1:.5f}; acc:{2:.3f}'.format(epoch, iteration_loss/(i+1), iteration_accuracy/(i+1)))


Train: epoch: 0 -loss: 0.30243; acc:86.444
Test: epoch: 0 -loss: 0.58675; acc:74.000
Train: epoch: 100 -loss: 0.46001; acc:74.667
Test: epoch: 100 -loss: 0.59032; acc:71.250
Train: epoch: 200 -loss: 0.30321; acc:85.778
Test: epoch: 200 -loss: 0.60104; acc:71.750
Train: epoch: 300 -loss: 0.31729; acc:87.556
Test: epoch: 300 -loss: 0.63605; acc:70.000
Train: epoch: 400 -loss: 0.40223; acc:78.889
Test: epoch: 400 -loss: 0.63640; acc:72.500
Train: epoch: 500 -loss: 0.37140; acc:81.444
Test: epoch: 500 -loss: 0.62745; acc:71.250
Train: epoch: 600 -loss: 0.29138; acc:86.889
Test: epoch: 600 -loss: 0.60483; acc:72.500
Train: epoch: 700 -loss: 0.27713; acc:87.444
Test: epoch: 700 -loss: 0.58458; acc:74.000
Train: epoch: 800 -loss: 0.34358; acc:81.667
Test: epoch: 800 -loss: 0.62848; acc:73.000
Train: epoch: 900 -loss: 0.29447; acc:87.889
Test: epoch: 900 -loss: 0.60587; acc:73.500
Train: epoch: 1000 -loss: 0.52971; acc:80.556
Test: epoch: 1000 -loss: 0.59668; acc:74.000


In [ ]:
for epoch in range(epochs):
  epoch_loss = 0  # Changed variable name for clarity
  epoch_acc = 0   # Changed variable name for clarity

  model.train()
  for i, data in enumerate(train_loader, 0):  # Start enumerate from 0 for clarity
    X, y = data
    y_pred = model(X.float())
    loss = BCE(y_pred, y.reshape(-1, 1).float())

    epoch_loss += loss.item()  # Accumulate loss values
    epoch_acc += accuracy(y_pred, y).item()  # Accumulate accuracy values

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  if epoch % print_epochs == 0:
    print(f'Train: epoch: {epoch} - loss: {epoch_loss/(i+1):.5f}; acc: {epoch_acc/(i+1):.3f}')  # Calculate and print average loss and accuracy

  epoch_loss = 0
  epoch_acc = 0
  model.eval()
  with torch.no_grad():  # Disable gradient calculation during evaluation
    for i, data in enumerate(test_loader, 0):  # Start enumerate from 0 for clarity
      X, y = data
      y_pred = model(X.float())
      loss = BCE(y_pred, y.reshape(-1, 1).float())
      epoch_loss += loss.item()  # Accumulate loss values
      epoch_acc += accuracy(y_pred, y).item()  # Accumulate accuracy values

  if epoch % print_epochs == 0:
    print(f'Test: epoch: {epoch} - loss: {epoch_loss/(i+1):.5f}; acc: {epoch_acc/(i+1):.3f}')  # Calculate and print average loss and accuracy

Train: epoch: 0 - loss: 0.55946; acc: 75.111
Test: epoch: 0 - loss: 0.60232; acc: 70.000
Train: epoch: 100 - loss: 0.50560; acc: 72.333
Test: epoch: 100 - loss: 0.56214; acc: 74.500
Train: epoch: 200 - loss: 0.34937; acc: 85.556
Test: epoch: 200 - loss: 0.54919; acc: 75.750
Train: epoch: 300 - loss: 0.37595; acc: 82.000
Test: epoch: 300 - loss: 0.78106; acc: 66.000
Train: epoch: 400 - loss: 0.33970; acc: 84.000
Test: epoch: 400 - loss: 0.57679; acc: 75.000
Train: epoch: 500 - loss: 0.35969; acc: 84.111
Test: epoch: 500 - loss: 0.58997; acc: 71.750
Train: epoch: 600 - loss: 0.38394; acc: 78.444
Test: epoch: 600 - loss: 0.53627; acc: 74.000
Train: epoch: 700 - loss: 0.39065; acc: 83.889
Test: epoch: 700 - loss: 0.52902; acc: 76.500
Train: epoch: 800 - loss: 0.34163; acc: 85.111
Test: epoch: 800 - loss: 0.53598; acc: 74.500
Train: epoch: 900 - loss: 0.39608; acc: 83.667
Test: epoch: 900 - loss: 0.54968; acc: 73.750
Train: epoch: 1000 - loss: 0.35275; acc: 85.333
Test: epoch: 1000 - loss: 